### ISSUE TITLE
google_instance machine type rule

### ISSUE THREAD

**Issue by ArthurSens** [terraform-linters/tflint-ruleset-google#1]
Just like any other cloud provider, google has a list of machine types that can be provisioned.

All possible machine types for a given project can be found with the Google Cloud API. See documentation [here](https://cloud.google.com/compute/docs/reference/rest/v1/machineTypes/list)

GCP also let's you create custom machine types, as you can see [here](https://www.terraform.io/docs/providers/google/r/compute_instance.html#machine_type) and [here](https://cloud.google.com/dataproc/docs/concepts/compute/custom-machine-types)

**Comment by wata727** [comment]
Yes, such rules are easy to understand and useful. It ’s a very good starting point.

First of all, I would like to consider how to generate rules from a static list, but do you know the GCP API specification repository? (Imagine something like [azure-rest-api-specs](https://github.com/Azure/azure-rest-api-specs))

**Comment by ArthurSens** [comment]
After doing some research, I found this:
`https://cloud.google.com/dataflow/docs/reference/rest`

I guess you can change `dataflow` on this link to any other resource like `https://cloud.google.com/pubsub/docs/reference/rest` for example....

Is that what you were looking for?

**Comment by ArthurSens** [comment]
Just found the docs for retrieving machine types :smiley: 

https://cloud.google.com/compute/docs/reference/rest/v1/machineTypes/list
