### ISSUE TITLE
Auto-generating rules using the discovery service

### ISSUE THREAD

**Issue by freddd** [terraform-linters/tflint-ruleset-google#3]
Hi @wata727 

We are using GCP and looking at using tflint, when researching writing something similar myself I came across this: https://developers.google.com/discovery - basically the metadata service for getting information about the apis. I figured I'd drop it here in case someone else wants to get going creating the autogenerated rules before I get a chance to.

**Comment by wata727** [comment]
Thank you for sharing. I'll look it at later.

I'm not working on this yet, but I think the [magic-modules](https://github.com/GoogleCloudPlatform/magic-modules) is a good source at the moment. The terraform-provider-google validation is generated from here.

On the other hand, using it as a source has the limitation that it can only generate rules that the `teraform plan` can detect.

**Comment by wyardley** [comment]
Agree, magic modules is probably the best thing to start with.

If you find a maintainer, they can probably get in touch with folks from GCP who can help on the GCP slack in the #terraform channel.
