### ISSUE TITLE
[proposal] Warn google_project_iam for conflicting

### ISSUE THREAD

**Issue by wata727** [terraform-linters/tflint-ruleset-google#34]
See https://www.terraform.io/docs/providers/google/r/google_project_iam.html

> Note: google_project_iam_policy cannot be used in conjunction with google_project_iam_binding, google_project_iam_member, or google_project_iam_audit_config or they will fight over what your policy should be.

> Note: google_project_iam_binding resources can be used in conjunction with google_project_iam_member resources only if they do not grant privilege to the same role.

**Comment by PatMyron** [comment]
tracking in https://github.com/terraform-linters/tflint-ruleset-google/issues/22
