### ISSUE TITLE
Magic Modules go generation cutover

### ISSUE THREAD

**Issue by wyardley** [terraform-linters/tflint-ruleset-google#384]
Just a heads up that Magic Modules now is using golang vs. Ruby to generate modules. You may need to make some adjustments next time you update your fork.

https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/reference/ruby-go-changes.md

**Comment by wata727** [comment]
Thank you for letting me know. I'll take that into consideration when I update next time.
