### ISSUE TITLE
Deep checking support

### ISSUE THREAD

**Issue by bhundven** [terraform-linters/tflint-ruleset-google#58]
Deep checking support does not currently work, as there isn't a way to pass credentials (and/or isn't documented). This may also be an "issue" with `tflint` since it only has options for AWS:

```
      --aws-access-key=ACCESS_KEY                 AWS access key used in deep check mode
      --aws-secret-key=SECRET_KEY                 AWS secret key used in deep check mode
      --aws-profile=PROFILE                       AWS shared credential profile name used in deep check mode
      --aws-creds-file=FILE                       AWS shared credentials file path used in deep checking
      --aws-region=REGION                         AWS region used in deep check mode
```

**Comment by wata727** [comment]
I'm just working to migrate the deep checking feature to the AWS ruleset plugin from the TFLint core. As soon as this is completed, I think that plugins such as Google will be able to provide deep checking.

For reference, what kind of things do you want to check with deep checking? Please let me know. Thank you.

**Comment by wata727** [comment]
Deep checking support is merged in https://github.com/terraform-linters/tflint-ruleset-google/pull/75
